# Generated by Django 4.2.5 on 2023-09-23 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('image', models.ImageField(upload_to='blog/img')),
                ('date', models.DateField(verbose_name=datetime.date.today)),
            ],
        ),
    ]
